version: "3.7"
services:
  client:
    image: suejohnmo/yolo-client:1.0
    build:
      context: .
      dockerfile: client.DockerFile
    ports:
      - 3000:3000
  backend:
    image: suejohnmo/yolo-backend:1.0
    build:
      context: .
      dockerfile: backend.DockerFile
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
